apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tic-tac-toe-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tic-tac-toe-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
